"""Build kaggle/kernel/run.py: src/ and bench/ embedded as a base64 tarball; runs the tests and the
benchmark on a Kaggle T4. Push with `uvx kaggle kernels push -p kaggle/kernel`."""

import base64
import io
import json
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
buf = io.BytesIO()
with tarfile.open(fileobj=buf, mode="w:gz") as tar:
    for d in ("src", "bench", "tests"):
        tar.add(ROOT / d, arcname=d, filter=lambda t: None if "__pycache__" in t.name else t)
blob = base64.b64encode(buf.getvalue()).decode()
out = ROOT / "kaggle" / "kernel"
out.mkdir(parents=True, exist_ok=True)
(
    out / "run.py"
).write_text(f'''"""mini-vllm: tests and benchmark on a Kaggle T4 (generated by kaggle/build.py)."""
import base64, io, os, shutil, subprocess, sys, tarfile
os.chdir("/kaggle/working")
tarfile.open(fileobj=io.BytesIO(base64.b64decode("{blob}")), mode="r:gz").extractall(".")
env = dict(os.environ, PYTHONPATH="src")
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "pytest", "fastapi", "uvicorn", "httpx"], check=True)
subprocess.run(["nvidia-smi"], check=False)
os.makedirs("results", exist_ok=True)
with open("results/t4-tests.txt", "w") as log:
    r = subprocess.run([sys.executable, "-m", "pytest", "-q", "tests"], env=env, stdout=log, stderr=subprocess.STDOUT)
print(open("results/t4-tests.txt").read()[-1500:])
subprocess.run([sys.executable, "bench/bench.py"], check=True, env=env)
shutil.rmtree("src"); shutil.rmtree("bench"); shutil.rmtree("tests")
''')
(out / "kernel-metadata.json").write_text(
    json.dumps(
        {
            "id": "amaanmithani/mini-vllm-bench",
            "title": "mini-vllm bench",
            "code_file": "run.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "machine_shape": "NvidiaTeslaT4",
            "enable_internet": True,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": [],
        },
        indent=2,
    )
)
print("built", len(blob), "bytes")
